-- ゲーム定義
CREATE TABLE GAME_DEFINITION (
    ID BIGINT NOT NULL,
    SIZE INT NOT NULL,
    CONSTRAINT GAME_DEFINITION_PK PRIMARY KEY (ID)
);

-- セル定義
CREATE TABLE CELL_DEFINITION (
    GAME_DEFINITION_ID BIGINT NOT NULL,
    HORIZONTAL_POSITION INT NOT NULL,
    VERTICAL_POSITION INT NOT NULL,
    ALIVE SMALLINT NOT NULL,
    CONSTRAINT CELL_DEFINITION_PK PRIMARY KEY (GAME_DEFINITION_ID, HORIZONTAL_POSITION, VERTICAL_POSITION),
    CONSTRAINT CELL_DEFINITION_FK1 FOREIGN KEY (GAME_DEFINITION_ID) REFERENCES GAME_DEFINITION (ID)
);

-- ゲーム
CREATE TABLE GAME (
    ID BIGINT NOT NULL,
    SIZE INT NOT NULL,
    CONSTRAINT GAME_PK PRIMARY KEY (ID)
);

-- セル
CREATE TABLE CELL (
    ID BIGINT NOT NULL,
    GAME_ID BIGINT NOT NULL,
    HORIZONTAL_POSITION INT NOT NULL,
    VERTICAL_POSITION INT NOT NULL,
    ALIVE SMALLINT NOT NULL,
    CONSTRAINT CELL_PK PRIMARY KEY (ID),
    CONSTRAINT CELL_FK1 FOREIGN KEY (GAME_ID) REFERENCES GAME (ID),
    CONSTRAINT CELL_UK1 UNIQUE (GAME_ID, HORIZONTAL_POSITION, VERTICAL_POSITION)
);

-- セル関連
CREATE TABLE CELL_RELATION (
    MAIN_CELL_ID BIGINT NOT NULL,
    NEIGHBOR_CELL_ID BIGINT NOT NULL,
    CONSTRAINT CELL_RELATION_PK PRIMARY KEY (MAIN_CELL_ID, NEIGHBOR_CELL_ID),
    CONSTRAINT CELL_RELATION_FK1 FOREIGN KEY (MAIN_CELL_ID) REFERENCES CELL (ID),
    CONSTRAINT CELL_RELATION_FK2 FOREIGN KEY (NEIGHBOR_CELL_ID) REFERENCES CELL (ID)
);
